import { useState } from 'react';
import { X, Copy, Download, Check, FileText, Globe, Map, Bell } from 'lucide-react';

// ─── Helpers ───────────────────────────────────────────────────────────────────

const fmtTime = (iso) =>
  new Date(iso).toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: true,
  });

const SEVERITY_STYLES = {
  CRITICAL: { pill: 'bg-red-950/60 text-[#E8363D] border-[#E8363D]',    dot: 'bg-[#E8363D]' },
  HIGH:     { pill: 'bg-orange-950/60 text-orange-400 border-orange-500', dot: 'bg-orange-400' },
  MODERATE: { pill: 'bg-yellow-950/60 text-yellow-400 border-yellow-500', dot: 'bg-yellow-400' },
  LOW:      { pill: 'bg-green-950/60 text-green-400 border-green-700',    dot: 'bg-green-400'  },
};

const SeverityPill = ({ level }) => {
  const s = SEVERITY_STYLES[level] ?? SEVERITY_STYLES.MODERATE;
  return (
    <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded border text-[10px] font-black uppercase tracking-widest ${s.pill}`}>
      <span className={`w-1.5 h-1.5 rounded-full ${s.dot}`} />
      {level}
    </span>
  );
};

// ─── Plain-text builder for copy / download ────────────────────────────────────

const hr = '═'.repeat(62);
const thin = '─'.repeat(62);

const buildPlainText = (report, lang) => {
  const section = lang === 'hindi' ? report.hindi : report.english;
  const lines = [
    hr,
    `TRUTH MIRROR — OFFICIAL CIVIC ACCOUNTABILITY REPORT`,
    `Report ID : ${report.reportId}`,
    `Generated : ${fmtTime(report.generatedAt)}`,
    `Language  : ${lang === 'hindi' ? 'Hindi (हिंदी)' : 'English'}`,
    hr,
    '',
    section.title,
    '',
    thin,
    'EXECUTIVE SUMMARY',
    thin,
    section.executiveSummary,
    '',
    thin,
    'SEVERITY ANALYSIS',
    thin,
    section.severityAnalysis,
    '',
  ];

  if (lang !== 'hindi') {
    lines.push(thin, 'SYSTEMIC ISSUES IDENTIFIED', thin, section.systemicIssues, '');
  }

  lines.push(thin, lang === 'hindi' ? 'अनुशंसाएँ' : 'RECOMMENDED ACTIONS', thin);
  section.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`));
  lines.push('', thin, lang === 'hindi' ? 'निष्कर्ष' : 'CONCLUSION', thin, section.conclusion, '');
  return lines.join('\n');
};

const buildFullDownload = (report) => {
  const wardTable = [
    '',
    hr,
    'WARD-WISE BREAKDOWN',
    hr,
    `${'Ward'.padEnd(16)}${'Count'.padEnd(8)}${'Severity'.padEnd(12)}${'Top Issue'.padEnd(14)}Deadline`,
    thin,
    ...(report.wardAnalysis ?? []).map((w) =>
      `${w.ward.padEnd(16)}${String(w.unresolvedCount).padEnd(8)}${w.severityLevel.padEnd(12)}${(w.topIssue ?? '').padEnd(14)}${w.deadline ?? ''}`
    ),
    '',
    ...(report.wardAnalysis ?? []).map((w) => [
      `${w.ward}`,
      `  Action : ${w.recommendedAction}`,
      `  Dept   : ${w.responsibleDept}`,
    ].join('\n')),
  ].join('\n');

  const notifLog = [
    '',
    hr,
    'OFFICIAL NOTIFICATION LOG',
    hr,
    ...(report.notificationLog ?? []).map(
      (n, i) =>
        `${String(i + 1).padStart(2, '0')}. ${n.ward.padEnd(18)} ${n.official.padEnd(30)} Notified: ${fmtTime(n.notifiedAt)}  (${n.complaintsCount} complaints)`
    ),
    '',
    hr,
    'Generated by TRUTH MIRROR AI · Powered by Gemini 2.0 Flash',
    hr,
  ].join('\n');

  return buildPlainText(report, 'english')
    + '\n\n'
    + buildPlainText(report, 'hindi')
    + wardTable
    + notifLog;
};

// ─── Tab components ────────────────────────────────────────────────────────────

function ReportSection({ label, color = 'text-gray-400', children }) {
  return (
    <section className="space-y-2">
      <h4 className={`text-[10px] font-black uppercase tracking-widest ${color}`}>{label}</h4>
      {children}
    </section>
  );
}

function LangTab({ data, lang }) {
  if (!data) return <p className="text-gray-500 text-sm">No {lang} content available.</p>;
  return (
    <div className="space-y-5">
      <h3 className="text-white font-black text-sm leading-snug border-b border-[#1F1F2E] pb-3">
        {data.title}
      </h3>

      <ReportSection label="Executive Summary / कार्यपालक सारांश" color="text-[#E8363D]">
        <p className="text-gray-300 text-sm leading-relaxed">{data.executiveSummary}</p>
      </ReportSection>

      <ReportSection label="Severity Analysis / गंभीरता विश्लेषण" color="text-amber-400">
        <p className="text-gray-300 text-sm leading-relaxed">{data.severityAnalysis}</p>
      </ReportSection>

      {data.systemicIssues && (
        <ReportSection label="Systemic Issues Identified" color="text-yellow-400">
          <p className="text-gray-300 text-sm leading-relaxed">{data.systemicIssues}</p>
        </ReportSection>
      )}

      <ReportSection label="Recommended Actions / अनुशंसाएँ" color="text-green-400">
        <ol className="space-y-2.5">
          {(data.recommendations ?? []).map((rec, i) => (
            <li key={i} className="flex gap-3 text-sm">
              <span className="text-green-500 font-black tabular-nums flex-none">{i + 1}.</span>
              <span className="text-gray-300 leading-relaxed">{rec}</span>
            </li>
          ))}
        </ol>
      </ReportSection>

      <div className="bg-[#12122A] border border-[#1F1F2E] border-l-2 border-l-[#E8363D] rounded-lg p-4">
        <ReportSection label="Conclusion / निष्कर्ष" color="text-gray-500">
          <p className="text-gray-200 text-sm leading-relaxed italic">{data.conclusion}</p>
        </ReportSection>
      </div>
    </div>
  );
}

function WardTab({ wardAnalysis }) {
  if (!wardAnalysis?.length)
    return <p className="text-gray-500 text-sm text-center py-8">No ward breakdown available.</p>;

  return (
    <div className="space-y-3">
      {wardAnalysis.map((w, i) => (
        <div key={i} className="bg-[#12122A] border border-[#1F1F2E] rounded-xl p-4 space-y-3">
          {/* Header row */}
          <div className="flex items-start justify-between gap-2 flex-wrap">
            <div>
              <p className="text-white font-black text-sm">{w.ward}</p>
              <p className="text-gray-500 text-[10px] mt-0.5 uppercase tracking-wide">{w.responsibleDept}</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-[#E8363D] font-black text-lg tabular-nums">{w.unresolvedCount}</span>
              <span className="text-gray-500 text-xs">unresolved</span>
              <SeverityPill level={w.severityLevel} />
            </div>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div className="bg-[#0A0A0F] rounded-lg p-2.5 border border-[#1F1F2E]">
              <p className="text-gray-500 uppercase tracking-widest text-[9px] font-black mb-1">Top Issue</p>
              <p className="text-white font-semibold capitalize">{w.topIssue}</p>
            </div>
            <div className="bg-[#0A0A0F] rounded-lg p-2.5 border border-[#1F1F2E]">
              <p className="text-gray-500 uppercase tracking-widest text-[9px] font-black mb-1">Deadline</p>
              <p className={`font-black ${
                w.deadline?.includes('24') ? 'text-[#E8363D]' :
                w.deadline?.includes('3')  ? 'text-orange-400' :
                w.deadline?.includes('7')  ? 'text-yellow-400' : 'text-green-400'
              }`}>{w.deadline}</p>
            </div>
          </div>

          {/* Recommended action */}
          <div className="bg-[#0A0A0F] rounded-lg p-2.5 border border-[#1F1F2E]">
            <p className="text-gray-500 uppercase tracking-widest text-[9px] font-black mb-1">Recommended Action</p>
            <p className="text-gray-300 text-xs leading-relaxed">{w.recommendedAction}</p>
          </div>
        </div>
      ))}
    </div>
  );
}

function NotifTab({ log }) {
  if (!log?.length)
    return <p className="text-gray-500 text-sm text-center py-8">No notification log available.</p>;

  return (
    <div className="space-y-2">
      <p className="text-[10px] text-gray-500 uppercase tracking-widest font-black mb-3">
        {log.length} official{log.length !== 1 ? 's' : ''} notified via Truth Mirror Report System
      </p>
      {log.map((entry, i) => (
        <div key={i} className="bg-[#12122A] border border-[#1F1F2E] rounded-xl p-4">
          <div className="flex items-start justify-between gap-2 flex-wrap">
            <div className="flex-1 min-w-0">
              <p className="text-white font-black text-sm truncate">{entry.official}</p>
              <p className="text-gray-500 text-[11px] mt-0.5">{entry.ward} · {entry.complaintsCount} complaint{entry.complaintsCount !== 1 ? 's' : ''}</p>
            </div>
            <span className="flex-none flex items-center gap-1.5 bg-green-950/50 border border-green-900 text-green-400 text-[9px] font-black uppercase tracking-widest px-2 py-1 rounded-full">
              <span className="w-1.5 h-1.5 rounded-full bg-green-400" />
              Notified
            </span>
          </div>
          <p className="text-gray-600 text-[10px] mt-2.5 font-medium border-t border-[#1F1F2E] pt-2">
            🕐 {fmtTime(entry.notifiedAt)}
          </p>
        </div>
      ))}
    </div>
  );
}

// ─── Main Modal ────────────────────────────────────────────────────────────────

const TABS = [
  { id: 'english', label: 'English',    Icon: Globe    },
  { id: 'hindi',   label: 'हिंदी',       Icon: FileText },
  { id: 'wards',   label: 'Wards',      Icon: Map      },
  { id: 'log',     label: 'Notif. Log', Icon: Bell     },
];

export default function ReportModal({ report, onClose }) {
  const [activeTab, setActiveTab]   = useState('english');
  const [copied, setCopied]         = useState(false);

  const handleCopy = () => {
    const text = activeTab === 'wards' || activeTab === 'log'
      ? buildFullDownload(report)
      : buildPlainText(report, activeTab);
    navigator.clipboard?.writeText(text).catch(() => {});
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = buildFullDownload(report);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${report.reportId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className="fixed inset-0 z-[300] bg-black/85 backdrop-blur-sm flex items-end md:items-center justify-center p-0 md:p-4"
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-[#0A0A0F] border border-[#1F1F2E] rounded-t-2xl md:rounded-xl w-full md:max-w-2xl max-h-[92vh] flex flex-col shadow-2xl">

        {/* ── Modal header ── */}
        <div className="flex items-start justify-between px-5 pt-5 pb-4 border-b border-[#1F1F2E] flex-shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="w-2 h-2 rounded-full bg-[#E8363D] animate-pulse" />
              <h2 className="text-white font-black text-base uppercase tracking-wide">Government Report</h2>
            </div>
            <p className="text-[#E8363D] text-[10px] font-black uppercase tracking-widest">{report.reportId}</p>
            <p className="text-gray-500 text-[11px] mt-0.5">
              Generated {fmtTime(report.generatedAt)} &nbsp;·&nbsp;
              {report.totalUnresolved} unresolved across {report.wardCount} ward{report.wardCount !== 1 ? 's' : ''}
            </p>
          </div>
          <button
            onClick={onClose}
            className="bg-[#1F1F2E] hover:bg-gray-700 p-2 rounded-full transition-colors flex-none"
          >
            <X size={16} className="text-gray-400" />
          </button>
        </div>

        {/* ── Tabs ── */}
        <div className="flex border-b border-[#1F1F2E] overflow-x-auto flex-shrink-0">
          {TABS.map(({ id, label, Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id)}
              className={`flex items-center gap-1.5 px-4 py-3 text-[11px] font-black uppercase tracking-wider whitespace-nowrap transition-colors border-b-2 ${
                activeTab === id
                  ? 'text-[#E8363D] border-[#E8363D]'
                  : 'text-gray-500 border-transparent hover:text-gray-300'
              }`}
            >
              <Icon size={12} />
              {label}
            </button>
          ))}
        </div>

        {/* ── Scrollable content ── */}
        <div className="flex-1 overflow-y-auto px-5 py-5">
          {activeTab === 'english' && <LangTab data={report.english} lang="English" />}
          {activeTab === 'hindi'   && <LangTab data={report.hindi}   lang="Hindi"   />}
          {activeTab === 'wards'   && <WardTab wardAnalysis={report.wardAnalysis} />}
          {activeTab === 'log'     && <NotifTab log={report.notificationLog} />}
        </div>

        {/* ── Footer actions ── */}
        <div className="border-t border-[#1F1F2E] px-5 py-4 flex gap-3 flex-shrink-0">
          <button
            onClick={handleCopy}
            className="flex-1 bg-[#1F1F2E] hover:bg-gray-700 text-white font-bold py-3 rounded-lg flex items-center justify-center gap-2 text-sm transition-colors"
          >
            {copied ? <Check size={15} className="text-green-400" /> : <Copy size={15} />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="flex-1 bg-[#E8363D] hover:bg-red-700 text-white font-bold py-3 rounded-lg flex items-center justify-center gap-2 text-sm transition-colors shadow-[0_0_12px_rgba(232,54,61,0.3)]"
          >
            <Download size={15} />
            <span>Download .txt</span>
          </button>
        </div>
      </div>
    </div>
  );
}
